ALTER TABLE "Tenant" ADD COLUMN IF NOT EXISTS "address"       TEXT;
ALTER TABLE "Tenant" ADD COLUMN IF NOT EXISTS "directorName"  TEXT;
ALTER TABLE "Tenant" ADD COLUMN IF NOT EXISTS "directorPhone" TEXT;
ALTER TABLE "Tenant" ADD COLUMN IF NOT EXISTS "directorEmail" TEXT;
ALTER TABLE "Tenant" ADD COLUMN IF NOT EXISTS "eduId"         TEXT;